name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        runs-on: self-hosted
        container:
            image: cuaesd/aesd-autotest:24-unit-test
            options: --network host  #  Fix networking issue
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh

    full-test:
        runs-on: self-hosted
        container:
            image: cuaesd/aesd-autotest:24-assignment1
            options: --network host  #  Fix networking issue
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh

